// apps/server/src/components/Table/index.svelte
<script lang="ts">
  import QueryResult from '@latitude-sdk/query_result'
  import { Table, TableBlankSlate } from '@latitude-sdk/svelte/internal'
  import { useQuery } from '$lib/stores/queries'

  export let query: string

  let res = useQuery(query)
  $: data = $res.data as QueryResult
</script>

<TableBlankSlate loading={$res.isLoading} error={$res.error}>
  <Table {data} />
</TableBlankSlate>

// packages/client/react/src/lib/visualizations/raw/table/index.tsx
import type QueryResult from '@latitude-data/query_result'
import TableBlankSlate from '$src/lib/internal/shared/TableBlankSlate'
import TableComponent, {
  type Props as TableProps,
} from '$src/lib/internal/table'

type Props = Omit<TableProps, 'data'> & {
  isLoading: boolean
  data: QueryResult | null
  error?: Error
}

function Table({ data, isLoading = false, error, ...rest }: Props) {
  return (
    <TableBlankSlate loading={isLoading} data={data} error={error}>
      {data && <TableComponent data={data} {...rest} />}
    </TableBlankSlate>
  )
}

export { type Props }
export default Table
