// packages/client/react/src/lib/internal/table/index.tsx
import { default as TableRoot } from './table'
import { default as TableHeader } from './table-header'
import { default as TableBody } from './table-body'
import { default as TableHead } from './table-head'
import { default as TableRow } from './table-row'
import { default as TableCell } from './table-cell'

import { useMemo } from 'react'
import { useTable, useSortBy } from 'react-table'
import type QueryResult from '@latitude-data/query_result'
import { Card } from '$src/lib'
import VisualizationHeader from '$src/lib/internal/shared/VisualizationHeader'

interface Props {
  data: QueryResult
  className?: string
  title?: string
  description?: string
  download?: () => Promise<void>
}

function TableComponent({
  data,
  className,
  description,
  download,
  title,
}: Props) {
  const columns = useMemo(
    () =>
      data.fields.map((field) => ({
        Header: field.name,
        accessor: field.name,
      })),
    [data.fields],
  )

  const memoizedData = useMemo(() => data.toArray(), [data])

  const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } =
    useTable({ columns, data: memoizedData }, useSortBy)

  return (
    <Card.Root type='invisible' className='lat-flex lat-flex-col lat-gap-4'>
      <VisualizationHeader
        title={title}
        description={description}
        download={download}
      />
      <Card.Content type='invisible'>
        <TableRoot {...getTableProps()} className={className}>
          <TableHeader>
            {headerGroups.map((headerGroup) => (
              <TableRow
                {...headerGroup.getHeaderGroupProps()}
                key={`header-group-${headerGroup.id}`}
              >
                {headerGroup.headers.map((column) => (
                  <TableHead
                    {...column.getHeaderProps()}
                    key={`header-${column.id}`}
                  >
                    {column.render('Header')}
                  </TableHead>
                ))}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody {...getTableBodyProps()}>
            {rows.map((row, index) => {
              prepareRow(row)
              return (
                <TableRow {...row.getRowProps()} key={`row-${index}`}>
                  {row.cells.map((cell) => (
                    <TableCell
                      {...cell.getCellProps()}
                      key={`cell-${cell.column.id}-${row.id}`}
                    >
                      {cell.render('Cell')}
                    </TableCell>
                  ))}
                </TableRow>
              )
            })}
          </TableBody>
        </TableRoot>
      </Card.Content>
    </Card.Root>
  )
}

export { type Props }
export default TableComponent

// packages/client/svelte/src/lib/internal/ui/Table/Table.svelte
<script context="module" lang="ts">
  export type Props = {
    data: QueryResult
    class?: string | undefined
    description?: string
    download?: () => Promise<void> | undefined
    title?: string
  }
</script>

<script lang="ts">
  import * as Table from '$lib/internal/ui/_table'
  import QueryResult from '@latitude-data/query_result'
  import { Card } from '$lib'
  import { createTable, Render, Subscribe } from 'svelte-headless-table'
  import { readable } from 'svelte/store'
  import VisualizationHeader from '../_shared/VisualizationHeader.svelte'

  type $$Props = Props

  export let data: $$Props['data'] = new QueryResult({})
  export let description: $$Props['description'] = undefined
  export let download: $$Props['download'] = undefined
  export let title: $$Props['title'] = undefined

  let className: $$Props['class'] = undefined
  export { className as class }

  $: table = createTable(readable(data.toArray()))
  $: columns = table.createColumns(
    data.fields.map((field) =>
      table.column({ accessor: field.name, header: field.name })
    )
  )
  $: ({ headerRows, pageRows, tableAttrs, tableBodyAttrs } =
    table.createViewModel(columns))
</script>

<Card.Root type="invisible" class="flex flex-col gap-4">
  <VisualizationHeader {title} {description} {download} />
  <Card.Content type="invisible">
    <Table.Root {...$tableAttrs} class={className}>
      <Table.Header>
        {#each $headerRows as headerRow}
          <Subscribe rowAttrs={headerRow.attrs()}>
            <Table.Row>
              {#each headerRow.cells as cell (cell.id)}
                <Subscribe attrs={cell.attrs()} let:attrs props={cell.props()}>
                  <Table.Head {...attrs}>
                    <Render of={cell.render()} />
                  </Table.Head>
                </Subscribe>
              {/each}
            </Table.Row>
          </Subscribe>
        {/each}
      </Table.Header>
      <Table.Body {...$tableBodyAttrs}>
        {#each $pageRows as row (row.id)}
          <Subscribe rowAttrs={row.attrs()} let:rowAttrs>
            <Table.Row {...rowAttrs}>
              {#each row.cells as cell (cell.id)}
                <Subscribe attrs={cell.attrs()} let:attrs>
                  <Table.Cell {...attrs}>
                    <Render of={cell.render()} />
                  </Table.Cell>
                </Subscribe>
              {/each}
            </Table.Row>
          </Subscribe>
        {/each}
      </Table.Body>
    </Table.Root>
  </Card.Content>
</Card.Root>
