// packages/client/svelte/src/lib/internal/ui/_table/table-row.svelte
<script lang="ts">
  import { theme } from '@latitude-data/client'
  import type { HTMLAttributes } from 'svelte/elements'

  type $$Props = HTMLAttributes<HTMLTableRowElement> & {
    'data-state'?: unknown
  }

  let className: $$Props['class'] = undefined
  export { className as class }
</script>

<tr
  class={theme.ui.table.row.cssClass({ className })}
  {...$$restProps}
  on:click
  on:keydown
>
  <slot />
</tr>

// packages/client/react/src/lib/internal/table/table-row.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'

interface Props extends React.HTMLAttributes<HTMLTableRowElement> {
  className?: string
}

const TableRow = React.forwardRef<HTMLTableRowElement, Props>(
  ({ className, ...props }, ref) => (
    <tr
      ref={ref}
      className={theme.ui.table.row.cssClass({ className })}
      {...props}
    />
  ),
)
TableRow.displayName = 'TableRow'

export default TableRow
