// packages/client/svelte/src/lib/internal/ui/_table/table.svelte
<script lang="ts">
  import { theme } from '@latitude-data/client'
  import type { HTMLTableAttributes } from 'svelte/elements'

  type $$Props = HTMLTableAttributes

  let className: $$Props['class'] = undefined

  export { className as class }
</script>

<div class={theme.ui.table.container.cssClass({ className })}>
  <table class={theme.ui.table.root.cssClass({})} {...$$restProps}>
    <slot />
  </table>
</div>

// packages/client/react/src/lib/internal/table/table.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'

interface Props extends React.HTMLAttributes<HTMLTableElement> {
  className?: string
}

const Table = React.forwardRef<HTMLTableElement, Props>(
  ({ className, ...props }, ref) => (
    <div className={theme.ui.table.container.cssClass({ className })}>
      <table
        ref={ref}
        className={theme.ui.table.root.cssClass({})}
        {...props}
      />
    </div>
  ),
)
Table.displayName = 'Table'

export default Table
