// packages/client/svelte/src/lib/internal/ui/_table/table-body.svelte
<script lang="ts">
  import { theme } from '@latitude-data/client'
  import type { HTMLAttributes } from 'svelte/elements'

  type $$Props = HTMLAttributes<HTMLTableSectionElement>

  let className: $$Props['class'] = undefined
  export { className as class }
</script>

<tbody class={theme.ui.table.body.cssClass({ className })} {...$$restProps}>
  <slot />
</tbody>

// packages/client/react/src/lib/internal/table/table-body.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'

interface Props extends React.HTMLAttributes<HTMLTableSectionElement> {
  className?: string
}

const TableBody = React.forwardRef<HTMLTableSectionElement, Props>(
  ({ className, ...props }, ref) => (
    <tbody
      ref={ref}
      className={theme.ui.table.body.cssClass({ className })}
      {...props}
    />
  ),
)
TableBody.displayName = 'TableBody'

export default TableBody
