// packages/client/svelte/src/lib/internal/ui/_table/table-header.svelte
<script lang="ts">
  import { theme } from '@latitude-data/client'
  import type { HTMLAttributes } from 'svelte/elements'

  type $$Props = HTMLAttributes<HTMLTableSectionElement>

  let className: $$Props['class'] = undefined
  export { className as class }
</script>

<!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
<thead
  class={theme.ui.table.header.cssClass({ className })}
  {...$$restProps}
  on:click
  on:keydown
>
  <slot />
</thead>

// packages/client/react/src/lib/internal/table/table-header.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'

interface Props extends React.HTMLAttributes<HTMLTableSectionElement> {
  className?: string
}

const TableHeader = React.forwardRef<HTMLTableSectionElement, Props>(
  ({ className, ...props }, ref) => (
    <thead
      ref={ref}
      className={theme.ui.table.header.cssClass({ className })}
      {...props}
    />
  ),
)
TableHeader.displayName = 'TableHeader'

export default TableHeader
