// packages/client/svelte/src/lib/internal/ui/_table/table-cell.svelte
<script lang="ts">
  import { theme } from '@latitude-data/client'
  import type { HTMLTdAttributes } from 'svelte/elements'

  type $$Props = HTMLTdAttributes

  let className: $$Props['class'] = undefined

  export { className as class }
</script>

<td
  class={theme.ui.table.cell.cssClass({ className })}
  {...$$restProps}
  on:click
  on:keydown
>
  <slot />
</td>

// packages/client/react/src/lib/internal/table/table-cell.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'

interface Props extends React.TdHTMLAttributes<HTMLTableCellElement> {
  className?: string
}

const TableCell = React.forwardRef<HTMLTableCellElement, Props>(
  ({ className, ...props }, ref) => (
    <td
      ref={ref}
      className={theme.ui.table.cell.cssClass({ className })}
      {...props}
    />
  ),
)
TableCell.displayName = 'TableCell'

export default TableCell
