// packages/client/svelte/src/lib/internal/ui/_table/table-footer.svelte
<script lang="ts">
  import { theme } from '@latitude-data/client'
  import type { HTMLAttributes } from 'svelte/elements'

  type $$Props = HTMLAttributes<HTMLTableSectionElement>

  let className: $$Props['class'] = undefined
  export { className as class }
</script>

<tfoot class={theme.ui.table.footer.cssClass({ className })} {...$$restProps}>
  <slot />
</tfoot>

// packages/client/react/src/lib/internal/table/table-footer.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'

interface Props extends React.HTMLAttributes<HTMLTableSectionElement> {
  className?: string
}

const TableFooter = React.forwardRef<HTMLTableSectionElement, Props>(
  ({ className, ...props }, ref) => (
    <tfoot
      ref={ref}
      className={theme.ui.table.footer.cssClass({ className })}
      {...props}
    />
  ),
)
TableFooter.displayName = 'TableFooter'

export default TableFooter
