// packages/client/svelte/src/lib/ui/card/card-footer.svelte
<script context="module" lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'

  export type Props = HTMLAttributes<HTMLDivElement>
</script>

<script lang="ts">
  import { theme } from '@latitude-data/client'

  let className: Props['class'] = undefined
  export { className as class }
</script>

<div class={theme.ui.card.footerCssClass({ className })} {...$$restProps}>
  <slot />
</div>

// packages/client/react/src/lib/ui/card/card-footer.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'
interface Props extends React.HTMLAttributes<HTMLDivElement> {}

const CardFooter = React.forwardRef<HTMLDivElement, Props>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={theme.ui.card.footerCssClass({ className })}
      {...props}
    />
  ),
)
CardFooter.displayName = 'CardFooter'

export default CardFooter
