// packages/client/svelte/src/lib/ui/card/card-content.svelte
<script context="module" lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'

  export type Props = HTMLAttributes<HTMLDivElement>
</script>

<script lang="ts">
  import { theme } from '@latitude-data/client'

  let className: Props['class'] = undefined

  export { className as class }
</script>

<div class={theme.ui.card.contentCssClass({ className })} {...$$restProps}>
  <slot />
</div>

// packages/client/react/src/lib/ui/card/card-content.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'
type Props = React.HTMLAttributes<HTMLDivElement> & theme.ui.card.CardProps

const CardContent = React.forwardRef<HTMLDivElement, Props>(
  ({ className, type, ...props }, ref) => (
    <div
      ref={ref}
      className={theme.ui.card.contentCssClass({ type, className })}
      {...props}
    />
  ),
)
CardContent.displayName = 'CardContent'

export default CardContent
