// packages/client/react/src/lib/internal/shared/VisualizationHeader.tsx
import DownloadTooltip from './DownloadTooltip'
import React from 'react'

import type { theme } from '@latitude-data/client'
import { Card, Column, Row } from '$src/lib/ui'

interface VisualizationHeaderProps {
  title?: string
  description?: string
  headerType?: theme.ui.card.CardProps['type']
  headerAction?: (element: HTMLDivElement) => { destroy: () => void }
  download?: () => Promise<void>
}

const VisualizationHeader = React.forwardRef<
  HTMLDivElement,
  VisualizationHeaderProps
>(
  (
    { title, description, headerType = 'invisible', headerAction, download },
    ref,
  ) => {
    if (!title && !description && !download) return null

    return (
      <Card.Header type={headerType} action={headerAction} ref={ref}>
        <Row className='lat-gap-6'>
          <Column className='lat-flex-1 lat-gap-2'>
            {title && <Card.Title>{title}</Card.Title>}
            {description && <Card.Description>{description}</Card.Description>}
          </Column>
          {download && (
            <Column>
              <DownloadTooltip download={download} />
            </Column>
          )}
        </Row>
      </Card.Header>
    )
  },
)

export default VisualizationHeader

// packages/client/svelte/src/lib/internal/ui/_shared/VisualizationHeader.svelte
<script lang="ts">
  import { Card, Column, Row } from '$lib'
  import type { theme } from '@latitude-data/client'
  import DownloadTooltip from './DownloadTooltip.svelte'

  export let title: string | undefined = undefined
  export let description: string | undefined = undefined
  export let headerType: theme.ui.card.CardProps['type'] = 'invisible'
  export let headerAction:
    | ((element: HTMLDivElement) => { destroy(): void })
    | undefined = undefined
  export let download: (() => Promise<void> | undefined) | undefined
</script>

{#if title || description || download}
  <Card.Header type={headerType} action={headerAction}>
    <Row class="lat-gap-6">
      <Column class="lat-flex-1 lat-gap-2">
        {#if title}
          <Card.Title>{title}</Card.Title>
        {/if}
        {#if description}
          <Card.Description>{description}</Card.Description>
        {/if}
      </Column>
      {#if Boolean(download)}
        <Column>
          <DownloadTooltip {download} />
        </Column>
      {/if}
    </Row>
  </Card.Header>
{/if}
