// packages/client/react/src/lib/ui/button/index.tsx
import * as React from 'react'
import { Slot } from '@radix-ui/react-slot'
import { theme } from '@latitude-data/client'

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  asChild?: boolean
}

type Props = ButtonProps & {
  variant?: theme.ui.button.Variant
  size?: theme.ui.button.Size
}

const Button = React.forwardRef<HTMLButtonElement, Props>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button'
    return (
      <Comp
        type='button'
        className={theme.ui.button.cssClass({ variant, size, className })}
        ref={ref}
        {...props}
      />
    )
  },
)

Button.displayName = 'Button'

export default Button

// packages/client/svelte/src/lib/ui/button/index.svelte
<script context="module" lang="ts">
  export type Props = Omit<ButtonPrimitive.Props, 'class'> & {
    variant?: theme.ui.button.Variant
    size?: theme.ui.button.Size
    class?: string | null | undefined
  }
</script>

<script lang="ts">
  import { Button as ButtonPrimitive } from 'bits-ui'
  import { theme } from '@latitude-data/client'

  let className: Props['class'] = undefined

  export let variant: Props['variant'] = 'default'
  export let size: Props['size'] = 'default'
  export let builders: Props['builders'] = []
  export { className as class }
</script>

<ButtonPrimitive.Root
  {builders}
  type="button"
  class={theme.ui.button.cssClass({ variant, size, className })}
  {...$$restProps}
  on:click
  on:keydown
>
  <slot />
</ButtonPrimitive.Root>
