// packages/client/react/src/lib/ui/card/card.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'
type Props = React.HTMLAttributes<HTMLDivElement> & theme.ui.card.CardProps

const Card = React.forwardRef<HTMLDivElement, Props>(
  ({ className, type, ...props }, ref) => (
    <div
      ref={ref}
      className={theme.ui.card.rootCssClass({ type, className })}
      {...props}
    />
  ),
)
Card.displayName = 'Card'

export default Card

// packages/client/svelte/src/lib/ui/card/card.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import { theme } from '@latitude-sdk/client'

  type $$Props = HTMLAttributes<HTMLDivElement>;

  let className: $$Props["class"] = undefined;
  export { className as class };
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<div
  class={theme.ui.card.rootCssClass({ className })}
  {...$$restProps}
  on:click
  on:focusin
  on:focusout
  on:mouseenter
  on:mouseleave
>
  <slot />
</div>
