// packages/client/react/src/lib/ui/card/card-title.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'
type HeadingLevel = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
type Props = React.HTMLAttributes<HTMLHeadingElement> & {
  className?: string
  tag?: HeadingLevel
}

const CardTitle = React.forwardRef<HTMLParagraphElement, Props>(
  ({ className, tag, ...props }, ref) => {
    const Tag = tag || 'h3'

    return (
      <Tag
        ref={ref}
        className={theme.ui.card.titleCssClass({ className })}
        {...props}
      />
    )
  },
)
CardTitle.displayName = 'CardTitle'

export default CardTitle

// packages/client/svelte/src/lib/ui/card/card-title.svelte
<script context="module" lang="ts">
  export type HeadingLevel = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  export type Props = HTMLAttributes<HTMLHeadingElement> & {
    tag?: HeadingLevel
  }
</script>

<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'
  import { theme } from '@latitude-data/client'

  let className: Props['class'] = undefined
  export let tag: Props['tag'] = 'h3'
  export { className as class }
</script>

<svelte:element
  this={tag}
  class={theme.ui.card.titleCssClass({ className })}
  {...$$restProps}
>
  <slot />
</svelte:element>
