// packages/client/react/src/lib/ui/card/card-description.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'
interface Props extends React.HTMLAttributes<HTMLParagraphElement> {}

const CardDescription = React.forwardRef<HTMLParagraphElement, Props>(
  ({ className, ...props }, ref) => (
    <p
      ref={ref}
      className={theme.ui.card.descriptionCssClass({ className })}
      {...props}
    />
  ),
)
CardDescription.displayName = 'CardDescription'

export default CardDescription

// packages/client/svelte/src/lib/ui/card/card-description.svelte
<script context="module" lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'

  export type Props = HTMLAttributes<HTMLParagraphElement>
</script>

<script lang="ts">
  import { theme } from '@latitude-data/client'

  let className: Props['class'] = undefined
  export { className as class }
</script>

<p class={theme.ui.card.descriptionCssClass({ className })} {...$$restProps}>
  <slot />
</p>
