// packages/client/react/src/lib/internal/table/table-head.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'

interface Props extends React.ThHTMLAttributes<HTMLTableCellElement> {
  className?: string
}

const TableHead = React.forwardRef<HTMLTableCellElement, Props>(
  ({ className, ...props }, ref) => (
    <th
      ref={ref}
      className={theme.ui.table.head.cssClass({ className })}
      {...props}
    />
  ),
)
TableHead.displayName = 'TableHead'

export default TableHead

// packages/client/svelte/src/lib/internal/ui/_table/table-head.svelte
<script lang="ts">
  import { theme } from '@latitude-data/client'
  import type { HTMLThAttributes } from 'svelte/elements'

  type $$Props = HTMLThAttributes

  let className: $$Props['class'] = undefined
  export { className as class }
</script>

<th class={theme.ui.table.head.cssClass({ className })} {...$$restProps}>
  <slot />
</th>
