// packages/client/react/src/lib/internal/table/table-caption.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'

interface Props extends React.HTMLAttributes<HTMLTableCaptionElement> {
  className?: string
}

const TableCaption = React.forwardRef<HTMLTableCaptionElement, Props>(
  ({ className, ...props }, ref) => (
    <caption
      ref={ref}
      className={theme.ui.table.caption.cssClass({ className })}
      {...props}
    />
  ),
)
TableCaption.displayName = 'TableCaption'

export default TableCaption

// packages/client/svelte/src/lib/internal/ui/_table/table-caption.svelte
<script lang="ts">
  import { theme } from '@latitude-data/client'
  import type { HTMLAttributes } from 'svelte/elements'

  type $$Props = HTMLAttributes<HTMLTableCaptionElement>

  let className: $$Props['class'] = undefined
  export { className as class }
</script>

<caption
  class={theme.ui.table.caption.cssClass({ className })}
  {...$$restProps}
>
  <slot />
</caption>
