// packages/client/svelte/src/lib/ui/atoms/chart/FunnelChart.svelte
<script lang='ts'>
  import Echart, { type Props as EchartProps } from './_Echarts.svelte'
  import { type FunnelChartProps, theme } from '@latitude-sdk/client'
  const generate = theme.ui.chart.generateFunnelConfig

  type $$Props = Omit<EchartProps, 'options'> & FunnelChartProps

  export let width: $$Props['width']
  export let height: $$Props['height']
  export let locale: $$Props['locale'] = 'en'
  export let isComputing: $$Props['isComputing'] = false
  export let dataset: $$Props['dataset']
  export let animation: $$Props['animation']
  export let sort: $$Props['sort'] = 'descending'
  export let showColorGradient: $$Props['showColorGradient'] = false
  export let showLabels: $$Props['showLabels'] = true
  export let showDecal: $$Props['showDecal'] = false
  export let showLegend: $$Props['showLegend'] = false
</script>

<Echart
  options={generate({
    dataset,
    animation,
    sort,
    showColorGradient,
    showLabels,
    showDecal,
    showLegend
  })}
  {width}
  {height}
  {locale}
  {isComputing}
/>

// packages/client/react/src/lib/visualizations/raw/charts/FunnelChart.tsx
import Echart, {
  type Props as EchartProps,
} from '$src/lib/internal/shared/Echart'
import ChartWrapper, {
  type WrapperProps,
} from '$src/lib/internal/shared/ChartWrapper'
import {
  theme as client,
  type FunnelChartProps,
  type Dataset,
} from '@latitude-data/client'

const generate = client.ui.chart.generateFunnelConfig
type Props = Omit<EchartProps, 'options' | 'isComputing'> &
  Omit<FunnelChartProps, 'dataset'> &
  WrapperProps

function FunnelChart({
  data,
  isLoading,
  error,
  title,
  description,
  bordered = false,
  sort,
  width,
  height,
  locale = 'en',
  animation = true,
  orientation = 'vertical',
  showColorGradient = false,
  showLabels = true,
  showDecal = false,
  showLegend = false,
  download,
}: Props) {
  return (
    <ChartWrapper
      download={download}
      data={data}
      isLoading={isLoading}
      error={error}
      width={width}
      height={height}
      title={title}
      description={description}
      bordered={bordered}
    >
      {({
        dataset,
        contentHeight,
      }: {
        dataset: Dataset
        contentHeight?: number
      }) => (
        <Echart
          height={contentHeight}
          options={generate({
            dataset,
            animation,
            sort,
            orientation,
            showColorGradient,
            showLabels,
            showDecal,
            showLegend,
          })}
          width={width}
          locale={locale}
        />
      )}
    </ChartWrapper>
  )
}

export { type Props }
export default FunnelChart
