// packages/client/svelte/src/lib/internal/ui/chart/MixedChart.svelte
<script context="module" lang="ts">
  import { type Props as EchartProps } from './_Echarts.svelte'
  import { type CartesianChartProps, theme } from '@latitude-data/client'
  import Wrapper, { type WrapperProps } from './_Wrapper.svelte'

  export type MixedChartProps = Omit<EchartProps, 'options' | 'isComputing'> &
    Omit<CartesianChartProps, 'dataset'> &
    WrapperProps
</script>

<script lang="ts">
  import Echart from './_Echarts.svelte'
  const generate = theme.ui.chart.generateCartesianConfig

  export let data: MixedChartProps['data'] = null
  export let isLoading: MixedChartProps['isLoading'] = false
  export let error: MixedChartProps['error'] = null

  type $$Props = MixedChartProps
  export let x: $$Props['x']
  export let y: $$Props['y']
  export let title: $$Props['title'] = undefined
  export let description: $$Props['description'] = undefined
  export let bordered: $$Props['bordered'] = false
  export let sort: $$Props['sort'] = undefined
  export let width: $$Props['width'] = undefined
  export let height: $$Props['height'] = undefined
  export let locale: $$Props['locale'] = 'en'
  export let animation: $$Props['animation'] = true
  export let swapAxis: $$Props['swapAxis'] = false
  export let yTitle: $$Props['yTitle'] = ''
  export let xTitle: $$Props['xTitle'] = ''
  export let xFormat: $$Props['xFormat'] = undefined
  export let yFormat: $$Props['yFormat'] = undefined
  export let config: $$Props['config'] = undefined
  export let download: $$Props['download'] = undefined
</script>

<Wrapper
  {download}
  {data}
  {title}
  {description}
  {bordered}
  {isLoading}
  {error}
  {width}
  {height}
  let:dataset
  let:contentHeight
>
  <Echart
    height={contentHeight}
    options={generate({
      dataset,
      animation,
      x,
      y,
      sort,
      yTitle,
      xTitle,
      swapAxis,
      xFormat,
      yFormat,
      config,
    })}
    {width}
    {locale}
  />
</Wrapper>

// packages/client/react/src/lib/visualizations/raw/charts/MixedChart.tsx
import Echart, {
  type Props as EchartProps,
} from '$src/lib/internal/shared/Echart'
import ChartWrapper, {
  type WrapperProps,
} from '$src/lib/internal/shared/ChartWrapper'
import {
  theme as client,
  type CartesianChartProps,
  type Dataset,
} from '@latitude-data/client'

const generate = client.ui.chart.generateCartesianConfig
type Props = Omit<EchartProps, 'options' | 'isComputing'> &
  Omit<CartesianChartProps, 'dataset'> &
  WrapperProps

function MixedChart({
  data,
  isLoading,
  error,
  x,
  y,
  title,
  description,
  bordered = false,
  sort,
  width,
  height,
  locale = 'en',
  animation = true,
  swapAxis = false,
  xTitle = '',
  yTitle = '',
  xFormat,
  yFormat,
  config,
  download,
}: Props) {
  return (
    <ChartWrapper
      download={download}
      data={data}
      isLoading={isLoading}
      error={error}
      width={width}
      height={height}
      title={title}
      description={description}
      bordered={bordered}
    >
      {({
        dataset,
        contentHeight,
      }: {
        dataset: Dataset
        contentHeight?: number
      }) => (
        <Echart
          height={contentHeight}
          options={generate({
            dataset,
            animation,
            x,
            y,
            sort,
            yTitle,
            xTitle,
            swapAxis,
            xFormat,
            yFormat,
            config,
          })}
          width={width}
          locale={locale}
        />
      )}
    </ChartWrapper>
  )
}

export { type Props }
export default MixedChart
