// packages/client/svelte/src/lib/ui/atoms/chart/PieChart.svelte
<script lang='ts'>
  import Echart, { type Props as EchartProps } from './_Echarts.svelte'
  import { type PieChartProps, theme } from '@latitude-sdk/client'
  const generatePieConfig = theme.ui.chart.generatePieConfig

  type $$Props = Omit<EchartProps, 'options'> & PieChartProps

  export let dataset: $$Props['dataset']
  export let displayName: $$Props['displayName']
  export let animation: $$Props['animation']
  export let config: $$Props['config']
  export let width: $$Props['width']
  export let height: $$Props['height']
  export let locale: $$Props['locale'] = 'en'
  export let isComputing: $$Props['isComputing'] = false
</script>

<Echart
  options={generatePieConfig({ dataset, displayName, animation, config })}
  {width}
  {height}
  {locale}
  {isComputing}
/>

// packages/client/react/src/lib/visualizations/raw/charts/PieChart.tsx
import Echart, {
  type Props as EchartProps,
} from '$src/lib/internal/shared/Echart'
import ChartWrapper, {
  type WrapperProps,
} from '$src/lib/internal/shared/ChartWrapper'
import {
  theme as client,
  type PieChartProps,
  type Dataset,
} from '@latitude-data/client'

const generate = client.ui.chart.generatePieConfig
type Props = Omit<EchartProps, 'options' | 'isComputing'> &
  Omit<PieChartProps, 'dataset'> &
  WrapperProps

function PieChart({
  data,
  isLoading,
  error,
  title,
  description,
  bordered = false,
  sort,
  width,
  height,
  locale = 'en',
  animation = true,
  displayName,
  config,
  download,
}: Props) {
  return (
    <ChartWrapper
      download={download}
      data={data}
      isLoading={isLoading}
      error={error}
      width={width}
      height={height}
      title={title}
      description={description}
      bordered={bordered}
    >
      {({
        dataset,
        contentHeight,
      }: {
        dataset: Dataset
        contentHeight?: number
      }) => (
        <Echart
          height={contentHeight}
          options={generate({
            dataset,
            animation,
            sort,
            displayName,
            config,
          })}
          width={width}
          locale={locale}
        />
      )}
    </ChartWrapper>
  )
}

export { type Props }
export default PieChart
