// packages/client/svelte/src/lib/ui/row/index.svelte
<script context="module" lang="ts">
  export type Props = {
    class?: string
  }
</script>

<script lang="ts">
  import { theme } from '@latitude-data/client'

  type $$Props = Props

  let className: $$Props['class'] = undefined
  export { className as class }

  $: classes = theme.ui.row.cssClass({ className })
</script>

<div class={classes}>
  <slot />
</div>

// packages/client/react/src/lib/ui/row/index.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'
interface Props extends React.HTMLAttributes<HTMLDivElement> {}

const Row = React.forwardRef<HTMLDivElement, Props>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={theme.ui.row.cssClass({ className })}
      {...props}
    />
  ),
)
Row.displayName = 'Row'

export default Row
