// packages/client/svelte/src/lib/ui/alert/alert.svelte
<script context="module" lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'
  import type { AlertFontWeight } from './text.svelte'

  export type Props = HTMLAttributes<HTMLDivElement> &
    theme.ui.alert.Props & {
      html?: boolean
      centerText?: boolean
      fontWeight?: AlertFontWeight
    }
</script>

<script lang="ts">
  import { theme } from '@latitude-data/client'
  import AlertText from './text.svelte'

  type $$Props = Props

  let className: $$Props['class'] = undefined
  export let type: $$Props['type']
  export let scrollable: $$Props['scrollable'] = false
  export let centerText: $$Props['centerText'] = true
  export let fontWeight: $$Props['fontWeight'] = 'normal'
  export let html: $$Props['html'] = false
  export let secondary: $$Props['secondary'] = false
  export { className as class }

  $: styles = theme.ui.alert.cssClass({
    type,
    scrollable,
    secondary,
    className,
  })
  $: textColor = styles.properties.foreground
</script>

<div class={styles.root} {...$$restProps} role="alert">
  {#if html}
    <slot />
  {:else}
    <AlertText color={textColor} {fontWeight} centered={centerText}>
      <slot />
    </AlertText>
  {/if}
</div>

// packages/client/react/src/lib/ui/alert/index.tsx
import * as React from 'react'
import { theme } from '@latitude-data/client'
import AlertText from './text'

type Props = React.HTMLAttributes<HTMLDivElement> &
  theme.ui.alert.Props & {
    html?: boolean
    centerText?: boolean
    fontWeight?: 'normal' | 'bold'
  }

const Alert = React.forwardRef<HTMLDivElement, Props>(
  (
    {
      type,
      scrollable,
      centerText,
      fontWeight,
      html,
      secondary,
      className,
      children,
      ...props
    },
    ref,
  ) => {
    const styles = theme.ui.alert.cssClass({
      type,
      scrollable,
      secondary,
      className,
    })

    const textColor = styles.properties.foreground

    return (
      <div ref={ref} className={styles.root} {...props} role='alert'>
        {html ? (
          children
        ) : (
          <AlertText
            color={textColor}
            centered={centerText}
            fontWeight={fontWeight}
          >
            {children}
          </AlertText>
        )}
      </div>
    )
  },
)

export default Alert
