// packages/client/svelte/src/lib/ui/alert/text.svelte
<script context="module" lang="ts">
  import type { HTMLAttributes } from 'svelte/elements'
  import type {
    FontWeight,
    TextColor,
    ExtendsUnion,
  } from '@latitude-data/client'

  export type AlertFontWeight = ExtendsUnion<
    FontWeight,
    'normal' | 'medium' | 'bold'
  >
  export type Props = HTMLAttributes<HTMLDivElement> & {
    fontWeight?: AlertFontWeight
    color: TextColor
    centered?: boolean
  }
</script>

<script lang="ts">
  import Text from '../text'
  type $$Props = Props

  export let fontWeight: $$Props['fontWeight'] = 'normal'
  export let centered: $$Props['centered'] = true
  export let color: $$Props['color']
</script>

{#if fontWeight === 'normal'}
  <Text.H5 {color} {centered}><slot /></Text.H5>
{:else if fontWeight === 'medium'}
  <Text.H5M {color} {centered}><slot /></Text.H5M>
{:else if fontWeight === 'bold'}
  <Text.H5B {color} {centered}><slot /></Text.H5B>
{/if}

// packages/client/react/src/lib/ui/alert/text.tsx
import * as React from 'react'

import type { ExtendsUnion, FontWeight, TextColor } from '@latitude-data/client'
import Text from '../text'

export type AlertFontWeight = ExtendsUnion<
  FontWeight,
  'normal' | 'medium' | 'bold'
>

type Props = React.HTMLAttributes<HTMLDivElement> & {
  fontWeight?: AlertFontWeight
  color: TextColor
  centered?: boolean
  children: React.ReactNode
}

function AlertText({
  fontWeight = 'normal',
  centered = true,
  color,
  children,
  ...props
}: Props) {
  const TextComponent = (() => {
    switch (fontWeight) {
      case 'medium':
        return Text.H5M
      case 'bold':
        return Text.H5B
      default:
        return Text.H5
    }
  })()

  return (
    <TextComponent color={color} centered={centered} {...props}>
      {children}
    </TextComponent>
  )
}

export default AlertText
