// packages/client/svelte/src/lib/ui/text/Text.svelte
<script lang="ts">
  import { theme, type TextProps } from '@latitude-data/client'

  type $$Props = TextProps

  export let align: $$Props['align'] = 'left'
  export let as: $$Props['as'] = 'span'
  export let capitalize: $$Props['capitalize'] = false
  export let centered: $$Props['centered'] = false
  export let color: $$Props['color'] = 'foreground'
  export let ellipsis: $$Props['ellipsis'] = false
  export let leading: $$Props['leading'] = 'h4'
  export let lineThrough: $$Props['lineThrough'] = false
  export let size: $$Props['size'] = 'h4'
  export let spacing: $$Props['spacing'] = 'normal'
  export let underline: $$Props['underline'] = false
  export let uppercase: $$Props['uppercase'] = false
  export let weight: $$Props['weight'] = 'normal'
  export let whiteSpace: $$Props['whiteSpace'] = 'normal'
  export let wordBreak: $$Props['wordBreak'] = 'normal'

  let className: $$Props['className'] = undefined
  export { className as class }

  $: classes = theme.ui.text.cssClass({
    align,
    capitalize,
    centered,
    color,
    ellipsis,
    lineThrough,
    spacing,
    size,
    leading,
    underline,
    uppercase,
    weight,
    whiteSpace,
    wordBreak,
    className,
  })
</script>

<svelte:element this={as} class={classes}>
  <slot />
</svelte:element>

// packages/client/react/src/lib/ui/text/Text.tsx
import React from 'react'
import { theme, type TextProps } from '@latitude-data/client'

type Props = TextProps & React.HTMLAttributes<HTMLSpanElement>

function Text({
  align = 'left',
  as = 'span',
  capitalize = false,
  centered = false,
  color = 'foreground',
  ellipsis = false,
  leading = 'h4',
  lineThrough = false,
  size = 'h4',
  spacing = 'normal',
  underline = false,
  uppercase = false,
  weight = 'normal',
  whiteSpace = 'normal',
  wordBreak = 'normal',
  className,
  ...props
}: Props) {
  const Element = as
  return (
    <Element
      className={theme.ui.text.cssClass({
        align,
        capitalize,
        centered,
        color,
        ellipsis,
        lineThrough,
        spacing,
        size,
        leading,
        underline,
        uppercase,
        weight,
        whiteSpace,
        wordBreak,
        class: className,
      })}
      {...props}
    />
  )
}

export default Text
