// packages/client/react/src/lib/visualizations/raw/charts/ScatterChart.tsx
import Echart, {
  type Props as EchartProps,
} from '$src/lib/internal/shared/Echart'
import ChartWrapper, {
  type WrapperProps,
} from '$src/lib/internal/shared/ChartWrapper'
import {
  theme as client,
  type ScatterChartProps,
  type Dataset,
} from '@latitude-data/client'

const generate = client.ui.chart.generateScatterConfig
type Props = Omit<EchartProps, 'options' | 'isComputing'> &
  Omit<ScatterChartProps, 'dataset'> &
  WrapperProps

function ScatterChart({
  data,
  isLoading,
  error,
  x,
  y,
  title,
  description,
  bordered = false,
  width,
  height,
  locale = 'en',
  animation = true,
  sizeColumn,
  style = 'circle',
  swapAxis = false,
  xTitle = '',
  yTitle = '',
  xFormat,
  yFormat,
  config,
  download,
}: Props) {
  return (
    <ChartWrapper
      download={download}
      data={data}
      isLoading={isLoading}
      error={error}
      width={width}
      height={height}
      title={title}
      description={description}
      bordered={bordered}
    >
      {({
        dataset,
        contentHeight,
      }: {
        dataset: Dataset
        contentHeight?: number
      }) => (
        <Echart
          height={contentHeight}
          options={generate({
            dataset,
            animation,
            x,
            y,
            sizeColumn,
            style,
            yTitle,
            xTitle,
            swapAxis,
            xFormat,
            yFormat,
            config,
          })}
          width={width}
          locale={locale}
        />
      )}
    </ChartWrapper>
  )
}

export { type Props }
export default ScatterChart

// packages/client/svelte/src/lib/ui/atoms/chart/ScatterChart.svelte
<script lang='ts'>
  import Echart, { type Props as EchartProps } from './_Echarts.svelte'
  import { type ScatterChartProps, theme } from '@latitude-sdk/client'
  const generate = theme.ui.chart.generateScatterConfig

  type $$Props = Omit<EchartProps, 'options'> & ScatterChartProps

  export let width: $$Props['width']
  export let height: $$Props['height']
  export let locale: $$Props['locale'] = 'en'
  export let isComputing: $$Props['isComputing'] = false
  export let dataset: $$Props['dataset']
  export let animation: $$Props['animation']
  export let sizeColumn: $$Props['sizeColumn']
  export let style: $$Props['style'] = 'circle'
  export let x: $$Props['x']
  export let y: $$Props['y']
  export let yTitle: $$Props['yTitle']
  export let xTitle: $$Props['xTitle']
  export let swapAxis: $$Props['swapAxis'] = false
  export let xFormat: $$Props['xFormat']
  export let yFormat: $$Props['yFormat']
  export let config: $$Props['config']
</script>

<Echart
  options={generate({
    dataset,
    animation,
    x,
    y,
    sizeColumn,
    style,
    yTitle,
    xTitle,
    swapAxis,
    xFormat,
    yFormat,
    config
  })}
  {width}
  {height}
  {locale}
  {isComputing}
/>
